name: AttentionXML

model:
  hidden_size: 256
  layers_num: 1
  linear_size: [256]
  dropout: 0.2
  emb_trainable: True

train:
  batch_size: 32
  nb_epoch: 3
  swa_warmup: 10

valid:
  batch_size: 32

predict:
  batch_size: 32

path: models
